// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cn93ligtzGeNBFkkMqsHiFDy2nBw7ao',
    appId: '1:442240550183:web:6c128463bdb9ea1c381502',
    messagingSenderId: '442240550183',
    projectId: 'dealen-2d9e4',
    authDomain: 'dealen-2d9e4.firebaseapp.com',
    storageBucket: 'dealen-2d9e4.firebasestorage.app',
    measurementId: 'G-71NJY3Z968',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsGvDkMh5zb4Z75SaSfE1Ex8CARI0JWXU',
    appId: '1:442240550183:android:857ad533488d2366381502',
    messagingSenderId: '442240550183',
    projectId: 'dealen-2d9e4',
    storageBucket: 'dealen-2d9e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcFuBz8FwjyvTDCk2AQMG01jG7EYOsvFM',
    appId: '1:442240550183:ios:690688a694a5f0e9381502',
    messagingSenderId: '442240550183',
    projectId: 'dealen-2d9e4',
    storageBucket: 'dealen-2d9e4.firebasestorage.app',
    iosBundleId: 'com.dealen.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcFuBz8FwjyvTDCk2AQMG01jG7EYOsvFM',
    appId: '1:442240550183:ios:690688a694a5f0e9381502',
    messagingSenderId: '442240550183',
    projectId: 'dealen-2d9e4',
    storageBucket: 'dealen-2d9e4.firebasestorage.app',
    iosBundleId: 'com.dealen.app',
  );
}
